# Provider dependency lock — PLACEHOLDER STRUCTURE.
# A provider block with an EMPTY `hashes` list is REFUSED by the lock
# parser (R5-03): a checksum-less version can never become the attested
# provider-set authority. Real h1/zh checksums MUST be generated by
# `terraform providers lock` with the pinned provider versions during
# publication and attested by the conformance harness before this
# Profile Revision can become Active. Until then this is a legal empty
# lock (comments only), which attestation treats as "no providers".
