api_version: shaula.io/template-profile/v1
kind: RunnerTemplateProfile
platform: docker
runtime:
  protocol: terraform-cli/v1
  engine: terraform
  root_module: .
  required_version: ">= 1.9, < 2.0"
bindings_contract: shaula.bindings.docker/v1
schemas:
  bindings: schemas/bindings.schema.json
  parameters: schemas/parameters.schema.json

managed_resource_shape:
  - role: runner
    terraform_type: docker_container
    exact_count: 1
runner_image_digests:
  - localhost:5001/shaula-runner:2.337.0-bootstrap-v1@sha256:eb9fa6d0a3b8688f0f1daba9989f9323ad02b02c6d1cd36d49c2fddcb7fb6201
runtime_policy_digest: sha256:b4de26602d90b32d5faf6eef3f0c89f2f4e76d39a569c7b93175298c8cd8d7ec
