use super::{Code, Severity, StageId};
impl Code {
    pub fn definition(self) -> (&'static str, StageId, Severity, &'static str) {
        match self {
            Self::WorkerMigrationRequired => (
                "worker.migration_required",
                StageId::Authority,
                Severity::Warning,
                "Lifecycle state migration is required before new execution",
            ),
            Self::WorkerLaunchUnresolved => (
                "worker.launch_unresolved",
                StageId::ExecutionAdmission,
                Severity::Warning,
                "Worker launch or apply handover remains unresolved",
            ),
            Self::WorkerFencingUnknown => (
                "worker.fencing_unknown",
                StageId::ExecutionAdmission,
                Severity::Warning,
                "The previous worker process tree has not been proved stopped",
            ),
            Self::WorkerStateUnavailable => (
                "worker.state_unavailable",
                StageId::ResourceCleanup,
                Severity::Warning,
                "Authoritative lifecycle state is unavailable",
            ),
            Self::WorkerCleanupOnly => (
                "worker.cleanup_only",
                StageId::ResourceCleanup,
                Severity::Info,
                "Recovery permits cleanup only; Create cannot be repeated",
            ),
            Self::WorkerReceiptCommitted => (
                "worker.receipt_committed",
                StageId::Completion,
                Severity::Info,
                "State is sealed and the durable completion receipt can be replayed",
            ),
            Self::ObservationMissing => (
                "observation.missing",
                StageId::Authority,
                Severity::Warning,
                "Necessary evidence has not been collected",
            ),
            Self::ObservationStale => (
                "observation.stale",
                StageId::Authority,
                Severity::Warning,
                "The observation has expired",
            ),
            Self::ObservationConflict => (
                "observation.conflict",
                StageId::Authority,
                Severity::Warning,
                "Observation identity or ordering conflicts",
            ),
            Self::ObservationClockInvalid => (
                "observation.clock_invalid",
                StageId::Authority,
                Severity::Warning,
                "Observation time cannot be trusted",
            ),
            Self::ObservationUnclassifiedFailure => (
                "observation.unclassified_failure",
                StageId::Authority,
                Severity::Warning,
                "An observation failed without a safe classification",
            ),
            Self::ControlAuthContextPending => (
                "control.auth_context_pending",
                StageId::Authority,
                Severity::Info,
                "Authentication context is not ready",
            ),
            Self::ControlDependencyUnavailable => (
                "control.dependency_unavailable",
                StageId::Authority,
                Severity::Warning,
                "A required dependency is unavailable",
            ),
            Self::ControlOwnershipUnproven => (
                "control.ownership_unproven",
                StageId::Authority,
                Severity::Warning,
                "Ownership could not be proved",
            ),
            Self::ControlListenerNotReady => (
                "control.listener_not_ready",
                StageId::Demand,
                Severity::Info,
                "The listener is not ready",
            ),
            Self::ControlDemandUnavailable => (
                "control.demand_unavailable",
                StageId::Demand,
                Severity::Warning,
                "Demand is unavailable",
            ),
            Self::ControlInventoryUnavailable => (
                "control.inventory_unavailable",
                StageId::RunnerInventory,
                Severity::Warning,
                "Runner inventory is unavailable",
            ),
            Self::ControlRateLimited => (
                "control.rate_limited",
                StageId::Authority,
                Severity::Warning,
                "The backend reported a rate limit",
            ),
            Self::ControlDecommissioning => (
                "control.decommissioning",
                StageId::Authority,
                Severity::Info,
                "Fleet decommissioning has been requested",
            ),
            Self::CapacityTargetSatisfied => (
                "capacity.target_satisfied",
                StageId::Capacity,
                Severity::Info,
                "Effective capacity meets the observed target",
            ),
            Self::CapacityPolicyCeiling => (
                "capacity.policy_ceiling",
                StageId::Capacity,
                Severity::Info,
                "The capacity policy caps the target",
            ),
            Self::CapacityOccupancyLimit => (
                "capacity.occupancy_limit",
                StageId::Capacity,
                Severity::Warning,
                "Resource occupancy leaves no create headroom",
            ),
            Self::PoolMemberAtCap => (
                "pool.member_at_cap",
                StageId::Pool,
                Severity::Info,
                "A pool member reached its admission cap",
            ),
            Self::PoolNoEligibleMember => (
                "pool.no_eligible_member",
                StageId::Pool,
                Severity::Warning,
                "The actual candidate set is empty",
            ),
            Self::PoolInlineBackpressure => (
                "pool.inline_backpressure",
                StageId::Pool,
                Severity::Warning,
                "An inline pool member prevents admission",
            ),
            Self::ExecutionCreateSlotWait => (
                "execution.create_slot_wait",
                StageId::ExecutionAdmission,
                Severity::Info,
                "Waiting for a create execution slot",
            ),
            Self::ExecutionDestroySlotWait => (
                "execution.destroy_slot_wait",
                StageId::ExecutionAdmission,
                Severity::Info,
                "Waiting for a destroy execution slot",
            ),
            Self::LifecycleApplyOutcomeUnknown => (
                "lifecycle.apply_outcome_unknown",
                StageId::CreateEffect,
                Severity::Warning,
                "Apply may have started; its outcome is unknown",
            ),
            Self::LifecycleOperationFailed => (
                "lifecycle.operation_failed",
                StageId::CreateEffect,
                Severity::Error,
                "A recorded operation failed",
            ),
            Self::LifecycleBootstrapPending => (
                "lifecycle.bootstrap_pending",
                StageId::Bootstrap,
                Severity::Info,
                "Bootstrap has not completed",
            ),
            Self::LifecycleAwaitingOnline => (
                "lifecycle.awaiting_online",
                StageId::RunnerInventory,
                Severity::Info,
                "Waiting for runner inventory to confirm readiness",
            ),
            Self::LifecycleReadinessTimeout => (
                "lifecycle.readiness_timeout",
                StageId::RunnerInventory,
                Severity::Warning,
                "The controller classified a readiness timeout",
            ),
            Self::CleanupJobBusy => (
                "cleanup.job_busy",
                StageId::SafeRemoval,
                Severity::Info,
                "Ordinary cleanup is waiting for a busy job",
            ),
            Self::CleanupSafeDrainUnavailable => (
                "cleanup.safe_drain_unavailable",
                StageId::SafeRemoval,
                Severity::Warning,
                "Safe drain proof is unavailable",
            ),
            Self::CleanupRegistrationPending => (
                "cleanup.registration_pending",
                StageId::RegistrationCleanup,
                Severity::Warning,
                "Registration cleanup has not completed",
            ),
            Self::CleanupQuarantined => (
                "cleanup.quarantined",
                StageId::Completion,
                Severity::Warning,
                "The generation requires external verification",
            ),
            Self::CleanupHardLifetime => (
                "cleanup.hard_lifetime",
                StageId::Intent,
                Severity::Warning,
                "Maximum lifetime cleanup may interrupt a busy job",
            ),
            Self::CleanupNoCreateEffect => (
                "cleanup.no_create_effect",
                StageId::ResourceCleanup,
                Severity::Info,
                "The controller proved that create apply never started",
            ),
            Self::CleanupCompleted => (
                "cleanup.completed",
                StageId::Completion,
                Severity::Info,
                "The domain ledger records cleanup completion",
            ),
            Self::RolloutNoActiveRevision => (
                "rollout.no_active_revision",
                StageId::DependencyResolution,
                Severity::Warning,
                "No active dependency revision is available",
            ),
            Self::RolloutInputsIncompatible => (
                "rollout.inputs_incompatible",
                StageId::InputCompatibility,
                Severity::Warning,
                "Retained inputs do not satisfy the new revision",
            ),
            Self::RolloutBackendIncompatible => (
                "rollout.backend_incompatible",
                StageId::InputCompatibility,
                Severity::Warning,
                "The revision does not support this backend",
            ),
            Self::RolloutWaitingZeroOccupancy => (
                "rollout.waiting_zero_occupancy",
                StageId::Occupancy,
                Severity::Info,
                "Following the new revision requires zero occupancy",
            ),
            Self::RolloutCommitDeferred => (
                "rollout.commit_deferred",
                StageId::CommitFence,
                Severity::Info,
                "The rollout did not commit",
            ),
            Self::JobAssociationUnverified => (
                "job.association_unverified",
                StageId::Association,
                Severity::Info,
                "No verified generation association exists",
            ),
            Self::JobAssociationAmbiguous => (
                "job.association_ambiguous",
                StageId::Association,
                Severity::Warning,
                "The generation association is ambiguous",
            ),
            Self::JobDispatchNotObservable => (
                "job.dispatch_not_observable",
                StageId::ExecutionContext,
                Severity::Info,
                "Upstream job dispatch is not observable",
            ),
        }
    }
    pub fn as_str(self) -> &'static str {
        self.definition().0
    }
}
