//! Runner lifecycle ledger: generations, operations, sessions with epochs,
//! demand snapshots, job observations, acquisition intents and scale set
//! ownership state. All runner rows are namespaced by Fleet Key.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(RunnerGenerations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RunnerGenerations::Id)
                            .string_len(64)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::FleetKey)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::RunnerName)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::GenerationName)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::FleetRevision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::TemplateProfileKey)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::TemplateRevision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::TemplateArtifactDigest)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::AttestationId)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::InputsDigest)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::State)
                            .string_len(32)
                            .not_null()
                            .default("CreatePending"),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::Subphase)
                            .string_len(48)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::JitPhase)
                            .string_len(48)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::GithubRunnerId)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::WorkspacePath)
                            .text()
                            .not_null(),
                    )
                    // Protected opaque evidence (shaula_result body + digest).
                    .col(
                        ColumnDef::new(RunnerGenerations::ShaulaResultJson)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::ShaulaResultDigest)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerGenerations::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_generations_fleet_name")
                    .table(RunnerGenerations::Table)
                    .col(RunnerGenerations::FleetKey)
                    .col(RunnerGenerations::RunnerName)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(RunnerOperations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RunnerOperations::Id)
                            .string_len(64)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::GenerationId)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::Kind)
                            .string_len(16)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::State)
                            .string_len(48)
                            .not_null()
                            .default("Pending"),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::Attempts)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::NextRetryAt)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::SavedPlanPath)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::SavedPlanDigest)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::ProvenanceJson)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::LeaseOwner)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::LeaseExpiresAt)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RunnerOperations::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ScaleSetState::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ScaleSetState::FleetKey)
                            .string_len(128)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::ScaleSetId)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::Name)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::RunnerGroup)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::Fingerprint)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::State)
                            .string_len(64)
                            .not_null()
                            .default("Unbound"),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::AttemptId)
                            .string_len(64)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScaleSetState::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        session_tables::create_tables_part2(manager).await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Err(DbErr::Custom("migrations are forward-only".to_string()))
    }
}

use self::iden::*;

#[path = "m0004_lifecycle_tables_iden.rs"]
mod iden;

#[path = "m0004_session_tables.rs"]
mod session_tables;
