// Session, demand and observation table builders, split to keep the host
// migration file under 400 lines.
use sea_orm_migration::prelude::*;

use super::iden::*;

pub(crate) async fn create_tables_part2(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(FleetSessions::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(FleetSessions::FleetKey)
                        .string_len(128)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(FleetSessions::SessionId)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetSessions::Epoch)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetSessions::ScaleSetId)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(FleetSessions::MessageQueueUrl).text().null())
                .col(ColumnDef::new(FleetSessions::QueueToken).text().null())
                .col(
                    ColumnDef::new(FleetSessions::LastMessageId)
                        .big_integer()
                        .not_null()
                        .default(0),
                )
                .col(
                    ColumnDef::new(FleetSessions::CreatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(FleetDemand::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(FleetDemand::FleetKey)
                        .string_len(128)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(FleetDemand::TotalAssignedJobs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetDemand::UpdatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(JobObservations::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(JobObservations::Id)
                        .big_integer()
                        .primary_key()
                        .auto_increment(),
                )
                .col(
                    ColumnDef::new(JobObservations::FleetKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(JobObservations::MessageId)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(JobObservations::ObservationKind)
                        .string_len(32)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(JobObservations::RunnerRequestId)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(JobObservations::JobId)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(JobObservations::RunnerName)
                        .string_len(128)
                        .null(),
                )
                .col(
                    ColumnDef::new(JobObservations::ObservedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_job_obs_dedup")
                .table(JobObservations::Table)
                .col(JobObservations::FleetKey)
                .col(JobObservations::MessageId)
                .col(JobObservations::ObservationKind)
                .col(JobObservations::RunnerRequestId)
                .unique()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(AcquisitionIntents::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(AcquisitionIntents::Id)
                        .string_len(64)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::FleetKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::MessageId)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::RunnerRequestId)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::Epoch)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::State)
                        .string_len(32)
                        .not_null()
                        .default("AcquireStarting"),
                )
                .col(
                    ColumnDef::new(AcquisitionIntents::CreatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    Ok(())
}
