// Remaining fleet-side table builders, split to keep the migration
// file under 400 lines.
use sea_orm_migration::prelude::*;

use super::iden::*;

pub(crate) async fn create_remaining(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(FleetAuthHandoffs::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(FleetAuthHandoffs::FleetKey)
                        .string_len(128)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::DesiredProfileKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::DesiredRevision)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::ObservedProfileKey)
                        .string_len(128)
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::ObservedRevision)
                        .big_integer()
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::State)
                        .string_len(48)
                        .not_null()
                        .default("Pending"),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::CleanupOnly)
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::Attempts)
                        .big_integer()
                        .not_null()
                        .default(0),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::NextRetryAt)
                        .big_integer()
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::LeaseOwner)
                        .string_len(128)
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::LeaseExpiresAt)
                        .big_integer()
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetAuthHandoffs::Reason)
                        .string_len(128)
                        .null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(FleetChanges::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(FleetChanges::Id)
                        .string_len(64)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(FleetChanges::FleetKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetChanges::Revision)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(FleetChanges::Kind).string_len(48).not_null())
                .col(
                    ColumnDef::new(FleetChanges::State)
                        .string_len(32)
                        .not_null()
                        .default("Pending"),
                )
                .col(
                    ColumnDef::new(FleetChanges::Attempts)
                        .big_integer()
                        .not_null()
                        .default(0),
                )
                .col(
                    ColumnDef::new(FleetChanges::NextRetryAt)
                        .big_integer()
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetChanges::LeaseOwner)
                        .string_len(128)
                        .null(),
                )
                .col(
                    ColumnDef::new(FleetChanges::LeaseExpiresAt)
                        .big_integer()
                        .null(),
                )
                .col(ColumnDef::new(FleetChanges::Reason).string_len(128).null())
                .col(
                    ColumnDef::new(FleetChanges::CreatedAt)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(FleetChanges::UpdatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_fleet_changes_open")
                .table(FleetChanges::Table)
                .col(FleetChanges::State)
                .col(FleetChanges::NextRetryAt)
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(IdempotencyRecords::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(IdempotencyRecords::Id)
                        .string_len(64)
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::ResourceKind)
                        .string_len(48)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::ResourceKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::IdempotencyKey)
                        .string_len(200)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::RequestHash)
                        .string_len(128)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::ResponseStatus)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::ResponseBody)
                        .text()
                        .null(),
                )
                .col(
                    ColumnDef::new(IdempotencyRecords::CreatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_idem_unique")
                .table(IdempotencyRecords::Table)
                .col(IdempotencyRecords::ResourceKind)
                .col(IdempotencyRecords::ResourceKey)
                .col(IdempotencyRecords::IdempotencyKey)
                .unique()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(AuditRecords::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(AuditRecords::Seq)
                        .big_integer()
                        .primary_key()
                        .auto_increment(),
                )
                .col(
                    ColumnDef::new(AuditRecords::ResourceKind)
                        .string_len(48)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AuditRecords::Action)
                        .string_len(64)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AuditRecords::Actor)
                        .string_len(256)
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AuditRecords::ResourceKey)
                        .string_len(128)
                        .not_null(),
                )
                .col(ColumnDef::new(AuditRecords::Revision).big_integer().null())
                .col(
                    ColumnDef::new(AuditRecords::Outcome)
                        .string_len(64)
                        .not_null(),
                )
                .col(ColumnDef::new(AuditRecords::DetailJson).text().null())
                .col(
                    ColumnDef::new(AuditRecords::CreatedAt)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(Outbox::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(Outbox::Id)
                        .big_integer()
                        .primary_key()
                        .auto_increment(),
                )
                .col(
                    ColumnDef::new(Outbox::ResourceKind)
                        .string_len(48)
                        .not_null(),
                )
                .col(ColumnDef::new(Outbox::Topic).string_len(64).not_null())
                .col(ColumnDef::new(Outbox::Payload).text().not_null())
                .col(ColumnDef::new(Outbox::CreatedAt).big_integer().not_null())
                .col(ColumnDef::new(Outbox::ProcessedAt).big_integer().null())
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_outbox_pending")
                .table(Outbox::Table)
                .col(Outbox::ProcessedAt)
                .to_owned(),
        )
        .await?;

    // Keep foreign keys advisory: SQLite FK enforcement across lifecycle
    // states is managed by the store layer, not schema-level cascades.
    // FK cascades are advisory; store layer owns consistency.
    Ok(())
}
