//! Template Profile tables: profiles, immutable revisions (including
//! schema-sensitive binding plaintext), conformance attestations and the
//! content-addressed artifact registry.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(TemplateProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TemplateProfiles::Key)
                            .string_len(128)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::Incarnation)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::DesiredRevision)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::ActiveRevision)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::ObservedRevision)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::ActiveAttestationId)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::Status)
                            .string_len(32)
                            .not_null()
                            .default("Pending"),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::DeletionRequested)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfiles::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(TemplateProfileRevisions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::Id)
                            .big_integer()
                            .primary_key()
                            .auto_increment(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::ProfileKey)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::Revision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::ArtifactDigest)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::EngineRef)
                            .string_len(64)
                            .not_null(),
                    )
                    // Values derived only from the admitted artifact manifest.
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::Platform)
                            .string_len(32)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::BindingsContract)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::ManifestJson)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::LockDigest)
                            .string_len(128)
                            .null(),
                    )
                    // Schema-sensitive binding plaintext lives here by design
                    // (ADR-0009); the whole database is credential-grade.
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::BindingsJson)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::BindingsDigest)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::FleetInputPolicyJson)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::State)
                            .string_len(32)
                            .not_null()
                            .default("Pending"),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::Reason)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateProfileRevisions::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_tpl_revisions_key_rev")
                    .table(TemplateProfileRevisions::Table)
                    .col(TemplateProfileRevisions::ProfileKey)
                    .col(TemplateProfileRevisions::Revision)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(TemplateConformanceAttestations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::Id)
                            .string_len(128)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::ProfileKey)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::Revision)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::SubjectJson)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::SubjectDigest)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::Result)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::EvidenceDigest)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::SuiteName)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::SuiteVersion)
                            .string_len(64)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TemplateConformanceAttestations::CompletedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(TemplateArtifacts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TemplateArtifacts::Digest)
                            .string_len(128)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(TemplateArtifacts::SizeBytes)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TemplateArtifacts::State)
                            .string_len(32)
                            .not_null()
                            .default("Orphan"),
                    )
                    .col(
                        ColumnDef::new(TemplateArtifacts::ReferenceCount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TemplateArtifacts::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ProfileChanges::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ProfileChanges::Id)
                            .string_len(64)
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::ResourceKind)
                            .string_len(48)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::ProfileKey)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::Revision)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::Kind)
                            .string_len(48)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::State)
                            .string_len(32)
                            .not_null()
                            .default("Pending"),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::Attempts)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::NextRetryAt)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::LeaseOwner)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::LeaseExpiresAt)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::Reason)
                            .string_len(128)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProfileChanges::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Err(DbErr::Custom("migrations are forward-only".to_string()))
    }
}

use self::iden::*;

#[path = "m0002_template_tables_iden.rs"]
mod iden;
