//! Shared integration-test fixtures: fixed clock, router assembly,
//! artifact packaging, and authorized request helpers.
#![allow(dead_code)]

pub mod attestation_harness;
#[path = "../../../shaula-http/tests/support/mod.rs"]
pub mod oidc;

use std::sync::Arc;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use shaula_core::ports::Clock;
use shaula_core::registry::ControlPlaneStore;
use shaula_daemon::service::ControlPlane;
use shaula_store::registry_impl::SqliteControlPlane;
use shaula_store::Store;
use tower::ServiceExt;

#[derive(Debug)]
pub struct FixedClock(std::sync::atomic::AtomicI64);

impl Clock for FixedClock {
    fn now_unix_ms(&self) -> i64 {
        self.0.load(std::sync::atomic::Ordering::SeqCst)
    }
}

pub fn fixed_clock() -> Arc<FixedClock> {
    Arc::new(FixedClock(std::sync::atomic::AtomicI64::new(
        1_800_000_000_000,
    )))
}

pub struct TestPublisher {
    pub root: std::path::PathBuf,
}

impl shaula_http::router::ArtifactPublisher for TestPublisher {
    fn publish(&self, bytes: &[u8], declared_digest: &str) -> shaula_core::error::CoreResult<u64> {
        shaula_template::artifact::ArtifactStore::new(self.root.clone())
            .publish(bytes, declared_digest)
            .map(|p| p.size_bytes)
    }
}

/// The dependency lock shipped inside the fixture artifact: a real
/// provider block so the attestation provider-set authority is
/// exercised (a lock without providers would make the subject check
/// vacuous).
pub const FIXTURE_LOCK_HCL: &str = "# generated by terraform init\n\nprovider \"registry.terraform.io/hashicorp/kubernetes\" {\n  version     = \"2.23.0\"\n  constraints = \">= 1.9, < 2.0\"\n  hashes = [\n    \"h1:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\",\n    \"h1:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\",\n    \"zh:abababababababababababababababababababababababababababababababab\",\n  ]\n}\n";

/// A stand-in engine binary: attestation subjects are hashed against
/// THIS file, and a forged binary digest must fail.
pub fn fixture_engine(dir: &std::path::Path) -> std::path::PathBuf {
    std::fs::create_dir_all(dir).unwrap();
    let path = dir.join("terraform.cmd");
    std::fs::write(&path, "@echo off\r\nexit /b 0\r\n").unwrap();
    path
}

/// Assembles the router plus the store handle used to drive scans.
/// Returns the engine binary path too: it is the subject's
/// binary-digest authority (attest_body hashes the same file).
pub async fn build_app_with_scan() -> (axum::Router, Arc<SqliteControlPlane>, std::path::PathBuf) {
    let (app, control_plane, engine, _service) = build_app_with_service().await;
    (app, control_plane, engine)
}

/// Like [`build_app_with_scan`], but also returns the artifact root —
/// for tests that must manipulate the published artifact files in place
/// (e.g. the R7-03 unreadable-authority semantics).
pub async fn build_app_with_artifact_root() -> (
    axum::Router,
    Arc<SqliteControlPlane>,
    std::path::PathBuf,
    std::path::PathBuf,
) {
    let (app, control_plane, engine, _service, artifact_root) = build_app_inner().await;
    (app, control_plane, engine, artifact_root)
}

/// Assembles the router, the store handle and the service.
pub async fn build_app_with_service() -> (
    axum::Router,
    Arc<SqliteControlPlane>,
    std::path::PathBuf,
    Arc<ControlPlane>,
) {
    let (app, control_plane, engine, service, _artifact_root) = build_app_inner().await;
    (app, control_plane, engine, service)
}

async fn build_app_inner() -> (
    axum::Router,
    Arc<SqliteControlPlane>,
    std::path::PathBuf,
    Arc<ControlPlane>,
    std::path::PathBuf,
) {
    // R7-06: engine spawns run behind the fence supervisor, whose hidden
    // marker only the real `shaula` binary routes — point the supervisor
    // at it (a test-harness binary cannot route the marker itself).
    std::env::set_var("SHAULA_ENGINE_FENCE_EXE", env!("CARGO_BIN_EXE_shaula"));
    let tmp = tempfile::tempdir().unwrap();
    let artifact_root = tmp.path().join("artifacts");
    let data_dir = tmp.path().join("data");
    std::fs::create_dir_all(&artifact_root).unwrap();
    std::fs::create_dir_all(&data_dir).unwrap();
    let tmp_path = tmp.path().to_path_buf();
    std::mem::forget(tmp);

    let store = Store::open(&data_dir.join("test.db")).await.unwrap();
    store.migrate().await.unwrap();
    let control_plane = Arc::new(SqliteControlPlane::new(store, artifact_root.clone()));

    let engine_binary = fixture_engine(&tmp_path.join("engine"));
    let service = Arc::new(ControlPlane::new(
        control_plane.clone(),
        fixed_clock(),
        b"test-bindings-key".to_vec(),
        100,
        engine_binary.clone(),
    ));
    service.set_ready(true);
    let service_for_return = Arc::clone(&service);

    let router = shaula_http::router::build_router(shaula_http::router::AppState {
        fleets: service.clone(),
        profiles: service.clone(),
        health: service,
        oidc: oidc::oidc().await,
        body_limit: 64 * 1024 * 1024,
        request_body_limit: 64 * 1024 * 1024,
        artifact_publisher: Arc::new(TestPublisher {
            root: artifact_root.clone(),
        }),
    });
    (
        router,
        control_plane,
        engine_binary,
        service_for_return,
        artifact_root,
    )
}

pub fn fixture_artifact() -> (String, Vec<u8>) {
    let mut builder = tar::Builder::new(Vec::new());
    for (name, content) in [
        (
            "profile.yaml",
            "api_version: shaula.io/template-profile/v1\nkind: RunnerTemplateProfile\nplatform: kubernetes\nruntime:\n  protocol: terraform-cli/v1\n  engine: terraform\n  root_module: .\n  required_version: \">= 1.9, < 2.0\"\nbindings_contract: shaula.bindings.kubernetes/v1\nschemas:\n  bindings: schemas/bindings.schema.json\n  parameters: schemas/parameters.schema.json\nmanaged_resource_shape:\n  - role: bootstrap\n    terraform_type: kubernetes_secret_v1\n    exact_count: 1\n  - role: runner\n    terraform_type: kubernetes_pod_v1\n    exact_count: 1\nrunner_image_digests:\n  - ghcr.io/actions/actions-runner:2.323.0@sha256:3f2a1b9c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f8\nruntime_policy_digest: sha256:policy-v1\n",
        ),
        (".terraform.lock.hcl", FIXTURE_LOCK_HCL),
        ("schemas/bindings.schema.json", "{}"),
        ("schemas/parameters.schema.json", "{}"),
        ("main.tf", "resource \"kubernetes_secret_v1\" \"bootstrap\" {}\n"),
    ] {
        let mut header = tar::Header::new_gnu();
        header.set_size(content.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append_data(&mut header, name, content.as_bytes())
            .unwrap();
    }
    let tar_bytes = builder.into_inner().unwrap();
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::fast());
    std::io::Write::write_all(&mut encoder, &tar_bytes).unwrap();
    let bytes = encoder.finish().unwrap();
    let digest = {
        use sha2::Digest;
        let mut hasher = sha2::Sha256::new();
        hasher.update(&bytes);
        format!("sha256:{}", hex::encode(hasher.finalize()))
    };
    (digest, bytes)
}

pub fn authorized(method: &str, uri: &str, body: Option<String>) -> Request<Body> {
    let mut builder = Request::builder()
        .method(method)
        .uri(uri)
        .header("authorization", crate::common::oidc::bearer("fleet.read fleet.write fleet.retire template.read template.publish template.attest template.retire auth.read auth.write auth.retire"));
    // R10-05: conditional writes are mandatory — test PUTs are all
    // create-style re-assertions, so they carry If-None-Match: *.
    if method == "PUT" {
        builder = builder.header("if-none-match", "*");
    }
    match body {
        Some(body) => builder.body(Body::from(body)).unwrap(),
        None => builder.body(Body::empty()).unwrap(),
    }
}

pub const AUTH_PUT_BODY: &str = r#"{
    "kind": "pat",
    "token": "github_pat_test_token_bytes",
    "pat_principal": "octocat",
    "target_allowlist": [{"kind":"organization","owner":"example-org"}]
}"#;

pub const TEMPLATE_PUT_BODY: &str = r#"{
    "artifact_digest": "PLACEHOLDER",
    "engine_ref": "terraform",
    "bindings": {"namespace": "actions-runners", "kubeconfig": "secret-kubeconfig"},
    "fleet_input_policy": {"size_class": ["standard"]}
}"#;

pub const FLEET_BODY: &str = r#"{
    "github": {
        "target": {"kind":"organization","owner":"example-org"},
        "auth_profile_ref": "prod-app",
        "scale_set_name": "shaula-x64",
        "runner_group": "Default",
        "labels": ["shaula-x64"]
    },
    "capacity": {"min_runners": 0, "max_runners": 5},
    "template_profile_ref": "k8s-linux",
    "template_inputs": {}
}"#;

/// Recomputes the store-issued bindings commitment for a profile revision.
pub fn expected_bindings_digest(profile_key: &str, revision: i64) -> String {
    use hmac::Mac;
    let mut mac = hmac::Hmac::<sha2::Sha256>::new_from_slice(b"test-bindings-key").unwrap();
    mac.update(b"shaula.bindings_digest.v1");
    mac.update(format!("{profile_key}/{revision}").as_bytes());
    format!("bd1_{}", hex::encode(mac.finalize().into_bytes()))
}

pub fn put_with_idempotency(uri: &str, idem: &str, body: String) -> Request<Body> {
    let mut request = authorized("PUT", uri, Some(body));
    request
        .headers_mut()
        .insert("if-none-match", axum::http::HeaderValue::from_static("*"));
    request.headers_mut().insert(
        "idempotency-key",
        axum::http::HeaderValue::from_str(idem).unwrap(),
    );
    request
}

pub async fn get_json(app: &axum::Router, uri: &str) -> serde_json::Value {
    let response = app
        .clone()
        .oneshot(authorized("GET", uri, None))
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK, "GET {uri} must succeed");
    let body = axum::body::to_bytes(response.into_body(), 1 << 20)
        .await
        .unwrap();
    serde_json::from_slice(&body).unwrap()
}

/// Builds the full attestation body by recomputing every authority
/// member from the store: the lock digest, the provider set parsed from
/// the artifact's lock file, the engine binary digest of THE configured
/// engine, the admitted manifest's engine/images/policy, and the
/// bindings commitment via HMAC.
pub async fn attest_body(
    control_plane: &Arc<SqliteControlPlane>,
    artifact_digest: &str,
    bindings_digest: &str,
    engine_binary: &std::path::Path,
) -> String {
    let lock = control_plane
        .artifact_lock_digest(artifact_digest)
        .await
        .unwrap()
        .unwrap_or_default();
    // The manifest is the authority: the subject copies IT, never
    // invented values (a forged member must fail activation).
    let manifest_text = control_plane
        .artifact_manifest(artifact_digest)
        .await
        .unwrap()
        .unwrap_or_default();
    let manifest: shaula_core::template::ProfileManifest =
        serde_yaml::from_str(&manifest_text).unwrap();
    let images: Vec<String> = manifest
        .runner_image_digests
        .iter()
        .map(|i| format!("\"{i}\""))
        .collect();
    let images = images.join(", ");
    // Provider set recomputed from the SAME lock file the store holds.
    let lock_text = control_plane
        .artifact_lock_file(artifact_digest)
        .await
        .unwrap()
        .unwrap_or_default();
    let providers: Vec<String> = shaula_core::lockfile::parse_lock_providers(&lock_text)
        .unwrap()
        .iter()
        .map(|p| {
            format!(
                r#"{{"source": "{}", "version": "{}", "checksums_digest": "{}"}}"#,
                shaula_core::lockfile::provider_source(&p.source),
                p.version,
                p.checksums_digest
            )
        })
        .collect();
    let providers = providers.join(", ");
    let engine_binary_digest = {
        use sha2::Digest;
        let bytes = std::fs::read(engine_binary).unwrap();
        format!("sha256:{}", hex::encode(sha2::Sha256::digest(&bytes)))
    };
    format!(
        r#"{{
        "result": "passed",
        "subject": {{
            "artifact_digest": "{artifact_digest}",
            "dependency_lock_digest": "{lock}",
            "providers": [{providers}],
            "bindings_digest": "{bindings_digest}",
            "platform": "{platform}",
            "bindings_contract": "{contract}",
            "engine": {{"kind": "{engine_kind}", "required_version": "{engine_version}", "version": "1.9.8", "binary_digest": "{engine_binary_digest}"}},
            "runner_image_digests": [{images}],
            "runtime_policy_digest": "{policy}",
            "suite": {{"name": "shaula-template-conformance", "version": "v1"}}
        }},
        "suite": {{"name": "shaula-template-conformance", "version": "v1"}},
        "completed_at": 1800000000
    }}"#,
        platform = manifest.platform,
        contract = manifest.bindings_contract,
        engine_kind = manifest.runtime.engine,
        engine_version = manifest.runtime.required_version,
        policy = manifest.runtime_policy_digest,
    )
}

/// A docker-platform fixture artifact for incarnation-identity tests:
/// same shape as [`fixture_artifact`] but with the Docker authority.
pub fn fixture_artifact_docker() -> (String, Vec<u8>) {
    let manifest = "api_version: shaula.io/template-profile/v1\nkind: RunnerTemplateProfile\nplatform: docker\nruntime:\n  protocol: terraform-cli/v1\n  engine: terraform\n  root_module: .\n  required_version: \">= 1.9, < 2.0\"\nbindings_contract: shaula.bindings.docker/v1\nschemas:\n  bindings: schemas/bindings.schema.json\n  parameters: schemas/parameters.schema.json\nmanaged_resource_shape:\n  - role: runner\n    terraform_type: docker_container\n    exact_count: 1\nrunner_image_digests:\n  - ghcr.io/actions/actions-runner:2.323.0@sha256:3f2a1b9c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f8\nruntime_policy_digest: sha256:policy-v1\n";
    let mut builder = tar::Builder::new(Vec::new());
    for (name, content) in [
        ("profile.yaml", manifest),
        (".terraform.lock.hcl", FIXTURE_LOCK_HCL),
        ("schemas/bindings.schema.json", "{}"),
        ("schemas/parameters.schema.json", "{}"),
        ("main.tf", "resource \"docker_container\" \"runner\" {}\n"),
    ] {
        let mut header = tar::Header::new_gnu();
        header.set_size(content.len() as u64);
        header.set_mode(0o644);
        header.set_cksum();
        builder
            .append_data(&mut header, name, content.as_bytes())
            .unwrap();
    }
    let tar_bytes = builder.into_inner().unwrap();
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::fast());
    std::io::Write::write_all(&mut encoder, &tar_bytes).unwrap();
    let bytes = encoder.finish().unwrap();
    let digest = {
        use sha2::Digest;
        let mut hasher = sha2::Sha256::new();
        hasher.update(&bytes);
        format!("sha256:{}", hex::encode(hasher.finalize()))
    };
    (digest, bytes)
}

/// A SECOND-revision template body: same artifact, semantically changed
/// input policy — identical content is a durable NO-OP under R9-02, so a
/// genuine revision 2 must change something.
pub fn template_put_body_r2(digest: &str) -> String {
    TEMPLATE_PUT_BODY.replace("PLACEHOLDER", digest).replace(
        "\"fleet_input_policy\": {\"size_class\": [\"standard\"]}",
        "\"fleet_input_policy\": {\"size_class\": [\"standard\", \"large\"]}",
    )
}

/// An attestation PUT request with its REQUIRED `If-None-Match: *`
/// precondition (R10-05, spec 0005 §5).
pub fn attestation_put_request(uri: &str, body: String) -> Request<Body> {
    let mut req = authorized("PUT", uri, Some(body));
    req.headers_mut()
        .insert("if-none-match", axum::http::HeaderValue::from_static("*"));
    req
}
